### ISSUE TITLE
seems some resources missing?

### ISSUE THREAD

**Issue by huanle0610** [enovision/movieworld#1]
GET http://www.movieworld.cc/resources/plugins/raty/img/star-off.png 404 (Not Found)

**Comment by huanle0610** [comment]
knew it.
Change
app/view/panel/DetailMovieCard.js:188
From

``` html
 path: 'resources/plugins/raty/img'
```

TO

``` html
path: 'resources/javascript/raty/img'
```

**Comment by enovision** [comment]
Thanks @huanle0610, I have corrected the paths
