### ISSUE TITLE
help to understand the structure of the application

### ISSUE THREAD

**Issue by ghatfan99** [enovision/movieworld#2]
Hello,
first of all thanks for this application, i need your help to understand how it works, for just building a very simple application with CodeIgniter and extjs 6, my question is how i can connect them like you did? and just explain me the steps to do that.

I have CodeIgniter-3.0.6 and GPL ext-6.0.1, 

Regards

Gr

**Comment by enovision** [comment]
The easiest way to do this is to see ExtJS as the frontend application and CodeIgniter as the backend (server). Your ExtJS Ajax calls and form submits (also Ajax) are calling an URL that in fact is a call to a controller in your server (CodeIgniter). 

So the way I always do it is I have my ExtJS application installed in the root of the web server (from your hosting provider or your own XAMPP) and I have a folder I call "server".

In CodeIgniter I tell that the the root of CodeIgniter is: http:\mywebsite.com\server. Now this working as a kind of API (REST) server to my ExtJS application. In that "server" folder I install CodeIgniter.

I don't use the "view" from CodeIgniter, only the controller and the model. And some libraries and helpers. The libraries are great for interfacing with 3rdparty products like PHPExcel or FPDF, TCPDF. The TMDB class is also done in that way I believe. 

I use models only to communicate with the database and libraries to get data from outside my database. I don't like helpers so much, for I like to see where the function came from (class).

In the server folder you put an .htaccess with the following content:

```
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_URI} ^Codeigniter.*
RewriteRule ^(.*)$ /server/index.php?/main/$1 [L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /server/index.php?/main/$1 [L]

ErrorDocument 404 /index.php
```

Make sure that you have in the index.php of the "server" folder (CodeIgniter index.php) the following:

```
$system_path = '/var/www/your-app-folder/server/CodeIgniter/system'
```

The "/var/www/your-app-folder/" you can find when you put an info.php in the root of your application with just a:  

```
<?php
phpinfo();
```

It is the www htdocs folder of your server.

Everytime I need something from the server I use as URL something like: http:\mywebsite.com\server\actors\getactors

where "actors" is the CodeIgniter controller and "getactors" is the function within the "actors" controller. 

From there you can get your data and package it in a json (json_encode) and simply echo it in PHP.

```
 {
    success: true,
    records: [{ 
         id: 1,
         name: 'Clint Eastwood'
       },{
        id: 2,
        name: 'Matt Damon'
   }],
   total: 2
}
```

Don't forget to "un"json the response when it is returned from an Ajax call.
Ext.decode(...

Tell me more where you need some help.

Kind regards,

Johan
